[package]
name = "cmd"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
internal = { path = "../internal", version = "0.1.3"}
actix-web = "4.4.0"
tokio = { version = "1.0", features = ["full"] }
