[package]
name = "cmd"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
internal = { path = "../internal", version = "0.2.2"}
tokio = { version = "1.0", features = ["full"] }
